/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package punto.de.venta;

/**
 *
 * @author gustavo
 */
public class FrmPuntoVenta extends javax.swing.JFrame {
    private java.util.List<Articulo> listaArticulos;
private javax.swing.table.DefaultTableModel modeloTabla;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPuntoVenta.class.getName());

    /**
     * Creates new form FrmPuntoVenta
     */
    public FrmPuntoVenta() {
        initComponents();
        listaArticulos = new java.util.ArrayList<>();
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nombre", "Precio", "Stock", "Categoría", "Fecha"}
        );
        tablaProductos.setModel(modeloTabla);
        
        // Cargar datos viejos automáticamente
        try {
            java.util.List<Articulo> cargados = ManejadorArchivo.leerArticulos();
            if (cargados != null) {
                this.listaArticulos = cargados;
                actualizarTablaGrafica();
            }
        } catch (Exception e) {
            System.out.println("Sin datos previos o error al cargar: " + e.getMessage());
        }
    } // <- Esta llave cierra el constructor FrmPuntoVenta()
private void actualizarTablaGrafica() {
        modeloTabla.setRowCount(0);
        for (Articulo art : listaArticulos) {
            modeloTabla.addRow(new Object[]{
                art.getId(), 
                art.getNombre(), 
                art.getPrecio(), 
                art.getStock(), 
                art.getCategoria(), 
                art.getFechaIngreso()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnImportarCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Stock");

        jLabel5.setText("Fecha");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtFecha.setText("2024-05-17");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronica", "Ropa", "Abarrotes", "Otros" }));
        cboCategoria.addActionListener(this::cboCategoriaActionPerformed);

        jLabel6.setText("Departamento");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(this::btnGenerarPDFActionPerformed);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        btnEliminar.setText("Eliminar Artículo");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnImportarCSV.setText("Importar Lote CSV");
        btnImportarCSV.addActionListener(this::btnImportarCSVActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFecha))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtStock))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImportarCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerarPDF)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar)
                        .addComponent(btnGenerarPDF)
                        .addComponent(btnEliminar)
                        .addComponent(btnImportarCSV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        try {
            if (listaArticulos.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay datos para el reporte.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            String ruta = "Reporte_Inventario.pdf";
            com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
            documento.open();
try {
                com.itextpdf.text.Image imagenLogo = com.itextpdf.text.Image.getInstance("logo.jpg");
                imagenLogo.scaleToFit(70, 70); 
                imagenLogo.setAlignment(com.itextpdf.text.Image.ALIGN_LEFT); 
                documento.add(imagenLogo);
            } catch (Exception imgEx) {
                System.out.println("No se pudo cargar el logo: " + imgEx.getMessage());
            }
            
            com.itextpdf.text.BaseColor azulElegante = new com.itextpdf.text.BaseColor(26, 82, 118); 
            
            com.itextpdf.text.BaseColor grisClaro = new com.itextpdf.text.BaseColor(242, 244, 244); 
            
            
            com.itextpdf.text.Font fuenteTitulo = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_BOLD, 20, azulElegante);
            com.itextpdf.text.Font fuenteSubtitulo = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA, 10, com.itextpdf.text.BaseColor.GRAY);
            com.itextpdf.text.Font fuenteHeaders = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_BOLD, 11, com.itextpdf.text.BaseColor.WHITE);
            com.itextpdf.text.Font fuenteDatos = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA, 10, com.itextpdf.text.BaseColor.BLACK);

            
            com.itextpdf.text.Paragraph titulo = new com.itextpdf.text.Paragraph("REPORTE DE INVENTARIO", fuenteTitulo);
            titulo.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            documento.add(titulo);
            
            com.itextpdf.text.Paragraph subtitulo = new com.itextpdf.text.Paragraph("Punto de Venta - Generado el: " + java.time.LocalDate.now() + "\n\n", fuenteSubtitulo);
            subtitulo.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            documento.add(subtitulo);

            
            com.itextpdf.text.pdf.PdfPTable tablaPdf = new com.itextpdf.text.pdf.PdfPTable(6);
            tablaPdf.setWidthPercentage(100); 
            tablaPdf.setSpacingBefore(10f);

            
            String[] encabezados = {"ID", "Nombre", "Precio", "Stock", "Categoría", "Fecha"};
            for (String enc : encabezados) {
                com.itextpdf.text.pdf.PdfPCell celdaHeader = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Paragraph(enc, fuenteHeaders));
                celdaHeader.setBackgroundColor(azulElegante);
                celdaHeader.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                celdaHeader.setPadding(6);
                tablaPdf.addCell(celdaHeader);
            }

            
            int filaContador = 0;
            for (Articulo art : listaArticulos) {
                com.itextpdf.text.BaseColor colorFila = (filaContador % 2 == 0) ? com.itextpdf.text.BaseColor.WHITE : grisClaro;

                String[] campos = {
                    art.getId(),
                    art.getNombre(),
                    "$" + art.getPrecio(),
                    String.valueOf(art.getStock()),
                    art.getCategoria(),
                    art.getFechaIngreso().toString()
                };

                for (String campo : campos) {
                    com.itextpdf.text.pdf.PdfPCell celdaDato = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Paragraph(campo, fuenteDatos));
                    celdaDato.setBackgroundColor(colorFila);
                    celdaDato.setPadding(5);
                    
                    if(campo.equals(art.getNombre())) {
                        celdaDato.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_LEFT);
                    } else {
                        celdaDato.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                    }
                    tablaPdf.addCell(celdaDato);
                }
                filaContador++;
            }

            documento.add(tablaPdf);
            documento.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Reporte PDF con diseño generado con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al crear PDF: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            
            if (txtId.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || 
                txtPrecio.getText().trim().isEmpty() || txtStock.getText().trim().isEmpty() || txtFecha.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            String id = txtId.getText().trim();
            String nombre = txtNombre.getText().trim();
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            String categoria = cboCategoria.getSelectedItem().toString(); 
            java.time.LocalDate fecha = java.time.LocalDate.parse(txtFecha.getText().trim());

            
            for (Articulo art : listaArticulos) {
                if (art.getId().equalsIgnoreCase(id)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El ID ya existe.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            
            Articulo nuevo = new Articulo(id, nombre, precio, stock, categoria, fecha);
            listaArticulos.add(nuevo);
            
            ManejadorArchivo.guardarArticulos(listaArticulos);
            actualizarTablaGrafica();
            
            
            txtId.setText(""); txtNombre.setText(""); txtPrecio.setText(""); txtStock.setText("");

            javax.swing.JOptionPane.showMessageDialog(this, "¡Artículo guardado con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fecha incorrecta. Use: AAAA-MM-DD", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Precio y Stock deben ser números.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int filaSeleccionada = tablaProductos.getSelectedRow();

        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione el artículo que desea eliminar en la tabla.", 
                "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar este artículo?", 
            "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            try {
                
                listaArticulos.remove(filaSeleccionada);

                
                ManejadorArchivo.guardarArticulos(listaArticulos);

                
                actualizarTablaGrafica();

                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Artículo eliminado con éxito.", "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al eliminar: " + e.getMessage(), "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCSVActionPerformed
        
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Seleccionar catálogo CSV de importación");
        
        
        javax.swing.filechooser.FileNameExtensionFilter filtro = new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");
        selector.setFileFilter(filtro);

        int resultado = selector.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoElegido = selector.getSelectedFile();
            
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoElegido))) {
                String linea;
                int importados = 0;
                
                while ((linea = br.readLine()) != null) {
                    
                    if (linea.trim().isEmpty()) continue;
                    
                    String[] datos = linea.split(",");
                    
                    if (datos.length == 6) {
                        String id = datos[0].trim();
                        String nombre = datos[1].trim();
                        double precio = Double.parseDouble(datos[2].trim());
                        int stock = Integer.parseInt(datos[3].trim());
                        String categoria = datos[4].trim();
                        java.time.LocalDate fecha = java.time.LocalDate.parse(datos[5].trim());

                        
                        boolean repetido = false;
                        for (Articulo art : listaArticulos) {
                            if (art.getId().equalsIgnoreCase(id)) {
                                repetido = true;
                                break;
                            }
                        }

                        if (!repetido) {
                            Articulo nuevo = new Articulo(id, nombre, precio, stock, categoria, fecha);
                            listaArticulos.add(nuevo);
                            importados++;
                        }
                    }
                }

                
                if (importados > 0) {
                    ManejadorArchivo.guardarArticulos(listaArticulos);
                    actualizarTablaGrafica();
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "¡Importación exitosa! Se añadieron " + importados + " artículos nuevos.", 
                        "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "No se importaron registros nuevos (campos incorrectos o IDs duplicados).", 
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al leer el CSV: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImportarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPuntoVenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnImportarCSV;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
